### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by abasse** [pedrozadotdev/pocketblocks#36]
Thank you very much for the cool project. Could you please provide some details on how to build the project from the source code?

**Comment by pedrozadotdev** [comment]
Inside the proxy folder, just run `yarn run build:ci`. This will install all client and proxy dependencies, build the client and put it in the right place so you can build the go project...

**Comment by abasse** [comment]
Thanks. When I run go build in ther server folder, I receive following
error message

server/ui/embed.go:10:12: pattern all:dist: no matching files found

Do I need to create a dist folder within server/ui ?
How does the client get embedded in the golang app?

Sorry for all the questions. You help ist much appreciated.


Andre Pedroza ***@***.***> schrieb am Mi., 4. Sept. 2024,
21:10:
