### ISSUE TITLE
Error in the event to open another application

### ISSUE THREAD

**Issue by srcarvalho12** [pedrozadotdev/pocketblocks#41]
Hello, I encountered a problem in the event of opening another application. When adding the open application event through the click of a button, for example, it passes as a parameter in the undefined url, which causes the logged in user to log out and stay in this loop, the same thing happens for the utils.openApp function.

Por exemplo:
![image](https://github.com/user-attachments/assets/e2d2e537-20fb-4966-aa06-4e1b2c210f7e)

**Comment by pedrozadotdev** [comment]
@srcarvalho12 vê por favor se a  [v0.4.9](https://github.com/pedrozadotdev/pocketblocks/releases/tag/v0.4.9) corrigiu teu problema.

**Comment by srcarvalho12** [comment]
Sim, agora sim está funcional! Agradeço! Uma outra dúvida seria sobre o SDK, ainda está funcional?

**Comment by srcarvalho12** [comment]
Fazendo uns testes, encontrei um problema. Após criar uma nova aplicação e publicar, vou nas configurações e seleciono tal aplicativo como aplicativo inicial padrão, e entro com um usuario não admin, recebo o erro:

![image](https://github.com/user-attachments/assets/d5ac9687-bcdc-407c-adc1-21d0f0b02f33)

Antes funcionava, mas após a atualização recebo esse erro.

**Comment by pedrozadotdev** [comment]
Eu só publiquei o [create-pocketblocks-plugin](https://www.npmjs.com/package/create-pocketblocks-plugin) para criar plugins. A funcionalidade de [embarcar aplicativos](https://pocketblocks.pedroza.dev/v/portugues-brasil/outros/embedded) usa o SDK disponível no servidor. Na documentação eu só demonstrei como usar ele em Vanilla JS, mas tem a opção de usar com React também([$pbl.OpenblocksAppView](https://github.com/pedrozadotdev/pocketblocks/tree/main/client/packages/openblocks-sdk)).

Eu achei um bug aqui na parte de embarcar apps mas já estou corrigindo...

**Comment by srcarvalho12** [comment]
Maravilha, sem problemas, agradeço!

**Comment by pedrozadotdev** [comment]
Resolvido na [v0.4.10](https://github.com/pedrozadotdev/pocketblocks/releases/tag/v0.4.10). Não sei qual teu caso de uso, mas acredito que a funcionalidade de embarcar apps deva atender. Vou fechar essa issue, caso você encontre algum outro bug só abrir uma nova.
